import{a as b,i as l,S as w}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&i(y)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S=document.querySelector(".gallery");function g(r){const t=r.map(o=>`<li class="gallery-item">
	  <a class="gallery-link" href="${o.largeImageURL}">
		<img 
			class="gallery-image" 
			src="${o.webformatURL}" 
			alt="${o.tags}" loading="lazy"
			/>
        <div class="gallery-info">
        <p class="gallery-likes"><span>Likes:</span> ${o.likes}</p>
        <p class="gallery-views"><span>Views:</span> ${o.views}</p>
        <p class="gallery-comments"><span>Comments:</span> ${o.comments}</p>
        <p class="gallery-downloads"><span>Downloads:</span> ${o.downloads}</p>
      </div>    
	  </a>
    </li>
    `).join("");S.insertAdjacentHTML("beforeend",t)}const P="47026899-90f4472111ba4dcf335a9f60a",v="https://pixabay.com/api/";async function h(r,t=1){const o=new URLSearchParams({key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}),i=`${v}?${o}`;try{return(await b.get(i)).data}catch(e){throw iziToast.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topLeft"}),console.error("There was a problem with the fetch operation:",e),e}}let c="",n=1,d=0,f;const p=document.querySelector(".gallery"),L=document.querySelector(".form"),q=document.querySelector(".input"),u=document.querySelector(".loader"),m=document.querySelector(".loader-add"),a=document.querySelector(".button-load");L.addEventListener("submit",$);a.addEventListener("click",R);function E(){const r=p.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"})}async function $(r){if(r.preventDefault(),p.innerHTML="",c=q.value.trim(),n=1,!c){l.error({title:"Error",message:"Please enter a search query...",position:"topLeft"});return}u.style.display="block",a.style.display="none";try{const t=await h(c,n);if(d=t.totalHits,u.style.display="none",t.hits.length===0){p.innerHTML="",l.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",timeout:3e3}),L.reset();return}p.innerHTML="",g(t.hits),f=new w(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:300});const o=Math.ceil(d/15);n>=o?(a.style.display="none",l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topLeft",timeout:3e3})):a.style.display="block"}catch(t){u.style.display="none",l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topLeft"}),console.error("Error fetching images:",t)}}async function R(){n+=1,m.style.display="block",a.style.display="none";try{const r=await h(c,n);if(m.style.display="none",r.hits.length===0){a.style.display="none",l.info({title:"No More Results",message:"No more images available.",position:"topLeft",timeout:3e3});return}g(r.hits),E();const t=Math.ceil(d/15);n>=t?(a.style.display="none",l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topLeft",timeout:3e3})):a.style.display="block",f&&f.refresh()}catch(r){u.style.display="none",a.style.display="block",l.error({title:"Error",message:"Failed to fetch more images. Please try again later.",position:"topLeft"}),console.error("Error fetching more images:",r)}}
//# sourceMappingURL=index.js.map
